spring.application.name=workconnect-backend

# ======================================================
# DATABASE CONFIGURATION
# ======================================================

spring.datasource.url=jdbc:mysql://localhost:3306/workconnect?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================================================
# JPA / HIBERNATE
# ======================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

# ======================================================
# SERVER
# ======================================================

server.port=8080

# ======================================================
# LOGGING
# ======================================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ======================================================
# JWT CONFIGURATION
# ======================================================

# Secret key (must be at least 32 characters)
jwt.secret=NzQ1YzJhYjM5Y2EyZDk0MTg2M2Y4NjA4ZjY5Y2U2NmM5MzYxN2JmNzMwZjI5OWQ5NjQ2M2JmNzEyY2U4ZWVkNQ==

# Token validity (30 minutes)
jwt.expiration=1800000

# ======================================================
# SWAGGER
# ======================================================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs